### ISSUE TITLE
Bulk Client or Client with Bulk methods?

### ISSUE THREAD

**Issue by aamirMasood** [developerforce/Force.com-Toolkit-for-NET#326]
The [doc ](https://github.com/developerforce/Force.com-Toolkit-for-NET#creating-the-forceclient-or-bulkforceclient) shows BulkForceClient, but that class doesn't exist in the source code. Please update the same.

**Comment by wharri220** [comment]
Just realized the same issue when trying to work with the BulkForceClient per docs.

**Comment by ijason** [comment]
Per the source code comments: _Consolidated the bulk client into the ForceClient_
The bulk methods should be available with ForceClient.

**Comment by Zhaph** [comment]
I've updated the ReadMe as part of my pull request to add Upsert functionality to the ForceClient methods. ( #334 ).

Alternatively, there's a working example within the existing source control for Insert, Update and Delete as within the [BulkForceClientFunctionalTests file](https://github.com/developerforce/Force.com-Toolkit-for-NET/blob/master/tests/ForceToolkitForNET.Tests/BulkForceClientFunctionalTests.cs).

**Comment by xantari** [comment]
Yo salesforce people, the documentation is still referencing BulkForceClient which has not been around for awhile. Please update!

**Comment by jacobjmarks** [comment]
This issue is still relevant. Documentation needs to be updated regarding the (non-existent) `BulkForceClient`.
